#!/bin/sh

mkdir -p ~/bin/
ln -sf `pwd`/bin/twig ~/bin/twig

if [[ `which twig` ]]; then
  echo 'All set! Run `twig` to list your local branches.'
else
  echo 'Argh! Something went wrong. Please try symlinking ./bin/twig to ~/bin/twig and ensure that ~/bin is in your $PATH, or contact rondevera on GitHub.'
fi
